//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;



public class Static_Round_t
{
    
    public int Id;
    
    public System.Collections.Generic.List<string> EnemyList;
    
    public float HpAdd;
    
    public float ATKAdd;
    
    public int Coin;
    
    public int Gem;
    
    public Static_Round_t(ref System.Collections.Generic.Dictionary<string, string> rValueSet)
    {
             String str_Id = rValueSet["Id"];
             Id = Utils.IntParseByString(str_Id);


             String str_EnemyList = rValueSet["EnemyList"];
             EnemyList = Utils.ParseStrings(str_EnemyList, ';');


             String str_HpAdd = rValueSet["HpAdd"];
             HpAdd = Utils.FloatParseByString(str_HpAdd);


             String str_ATKAdd = rValueSet["ATKAdd"];
             ATKAdd = Utils.FloatParseByString(str_ATKAdd);


             String str_Coin = rValueSet["Coin"];
             Coin = Utils.IntParseByString(str_Coin);


             String str_Gem = rValueSet["Gem"];
             Gem = Utils.IntParseByString(str_Gem);


    }
}
