//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;



public class Static_Character_t
{
    
    public string Id;
    
    public string Name;
    
    public float MoveSpeed;
    
    public float ATK;
    
    public float Crit;
    
    public float CritDamage;
    
    public float HP;
    
    public float ATKSpeed;
    
    public float ATKRange;
    
    public string Weapon;
    
    public Static_Character_t(ref System.Collections.Generic.Dictionary<string, string> rValueSet)
    {
             String str_Id = rValueSet["Id"];
             Id = str_Id;


             String str_Name = rValueSet["Name"];
             Name = str_Name;


             String str_MoveSpeed = rValueSet["MoveSpeed"];
             MoveSpeed = Utils.FloatParseByString(str_MoveSpeed);


             String str_ATK = rValueSet["ATK"];
             ATK = Utils.FloatParseByString(str_ATK);


             String str_Crit = rValueSet["Crit"];
             Crit = Utils.FloatParseByString(str_Crit);


             String str_CritDamage = rValueSet["CritDamage"];
             CritDamage = Utils.FloatParseByString(str_CritDamage);


             String str_HP = rValueSet["HP"];
             HP = Utils.FloatParseByString(str_HP);


             String str_ATKSpeed = rValueSet["ATKSpeed"];
             ATKSpeed = Utils.FloatParseByString(str_ATKSpeed);


             String str_ATKRange = rValueSet["ATKRange"];
             ATKRange = Utils.FloatParseByString(str_ATKRange);


             String str_Weapon = rValueSet["Weapon"];
             Weapon = str_Weapon;


    }
}
