//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;



public class Static_Card_t
{
    
    public string Id;
    
    public string Name;
    
    public string Des;
    
    public string Icon;
    
    public int Quality;
    
    public int Weight;
    
    public int CanRepeat;
    
    public int Type;
    
    public string SkillId;
    
    public int LifeTime;
    
    public Static_Card_t(ref System.Collections.Generic.Dictionary<string, string> rValueSet)
    {
             String str_Id = rValueSet["Id"];
             Id = str_Id;


             String str_Name = rValueSet["Name"];
             Name = str_Name;


             String str_Des = rValueSet["Des"];
             Des = str_Des;


             String str_Icon = rValueSet["Icon"];
             Icon = str_Icon;


             String str_Quality = rValueSet["Quality"];
             Quality = Utils.IntParseByString(str_Quality);


             String str_Weight = rValueSet["Weight"];
             Weight = Utils.IntParseByString(str_Weight);


             String str_CanRepeat = rValueSet["CanRepeat"];
             CanRepeat = Utils.IntParseByString(str_CanRepeat);


             String str_Type = rValueSet["Type"];
             Type = Utils.IntParseByString(str_Type);


             String str_SkillId = rValueSet["SkillId"];
             SkillId = str_SkillId;


             String str_LifeTime = rValueSet["LifeTime"];
             LifeTime = Utils.IntParseByString(str_LifeTime);


    }
}
