//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;



public class Static_Skill_t
{
    
    public string Id;
    
    public string Name;
    
    public string Des;
    
    public int Type;
    
    public float Value;
    
    public float Cool;
    
    public Static_Skill_t(ref System.Collections.Generic.Dictionary<string, string> rValueSet)
    {
             String str_Id = rValueSet["Id"];
             Id = str_Id;


             String str_Name = rValueSet["Name"];
             Name = str_Name;


             String str_Des = rValueSet["Des"];
             Des = str_Des;


             String str_Type = rValueSet["Type"];
             Type = Utils.IntParseByString(str_Type);


             String str_Value = rValueSet["Value"];
             Value = Utils.FloatParseByString(str_Value);


             String str_Cool = rValueSet["Cool"];
             Cool = Utils.FloatParseByString(str_Cool);


    }
}
