//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;



public class Static_Talent_t
{
    
    public int Id;
    
    public int Lv;
    
    public string Character;
    
    public System.Collections.Generic.List<int> Attr;
    
    public System.Collections.Generic.List<float> Value;
    
    public int Gem;
    
    public Static_Talent_t(ref System.Collections.Generic.Dictionary<string, string> rValueSet)
    {
             String str_Id = rValueSet["Id"];
             Id = Utils.IntParseByString(str_Id);


             String str_Lv = rValueSet["Lv"];
             Lv = Utils.IntParseByString(str_Lv);


             String str_Character = rValueSet["Character"];
             Character = str_Character;


             String str_Attr = rValueSet["Attr"];
             Attr = Utils.ParseIntStrings(str_Attr, ';');


             String str_Value = rValueSet["Value"];
             Value = Utils.ParseFloatStrings(str_Value, ';');


             String str_Gem = rValueSet["Gem"];
             Gem = Utils.IntParseByString(str_Gem);


    }
}
